
[build]
command = "npm run build"
publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirect and proxy all requests starting with /app/
# to app site on Netlify
[[redirects]]
  from = "/app/*"
  to = "https://acecrm-app-acesoft.netlify.app/:splat"
  status = 200
  force = true

# Fallback rule for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200